import 'App/Modules/Auth/routes'
import 'App/Modules/User/routes'
import 'App/Modules/Product/routes'
import 'App/Modules/Catalog/routes'
// import 'App/Modules/Offer/routes'
import 'App/Modules/Merchant/routes'
import 'App/Modules/Section/routes'
import 'App/Modules/Order/routes'
